class Cities {
  argentina = [
    { value: 'Buenos Aires', label: 'Buenos Aires' },
    { value: 'Rosario', label: 'Rosario' },
    { value: 'Ciudad de Córdoba', label: 'Ciudad de Córdoba' },
    { value: 'Mar del Plata', label: 'Mar del Plata' },
    { value: 'Salta', label: 'Salta' },
    { value: 'San Carlos Bariloche', label: 'San Carlos Bariloche' },
    { value: 'La Plata', label: 'La Plata' },
    { value: 'San Miguel de tucumá', label: 'San Miguel de tucumá' },
    { value: 'Ushuaia', label: 'Ushuaia' },
    { value: 'Ciudad de Santiago Del Estero', label: 'Ciudad de Santiago Del Estero' },
    { value: 'Bahía Blanca', label: 'Bahía Blanca' },
    { value: 'Resistencia', label: 'Resistencia' },
    { value: 'San Salvador de Jujuy', label: 'San Salvador de Jujuy' },
    { value: 'Posadas', label: 'Posadas' },
    { value: 'Comodoro Rivadavia', label: 'Comodoro Rivadavia' },
    { value: 'Ciudad de Santa Fe', label: 'Ciudad de Santa Fe' },
    { value: 'Trelew', label: 'Trelew' },
    { value: 'Paraná', label: 'Paranà' },
    { value: 'Concordia', label: 'Concordia' },
    { value: 'Río Gallegos', label: 'Río Gallegos' },
    { value: 'Ciudad de Corrientes', label: 'Ciudad de Corrientes' },
    { value: 'San Rafael', label: 'San Rafael' },
    { value: 'San Juan', label: 'San Juan' },
    { value: 'Puerto Madryn', label: 'Puerto Madryn' },
    { value: 'Ciudad de Santa Rosa', label: 'Ciudad de Santa Rosa' },
    { value: 'Rio Grande', label: 'Rio Grande' },
    { value: 'San Fernando del Valle de Catamarca', label: 'San Fernando del Valle de Catamarca' },
    { value: 'Cipolletti', label: 'Cipolletti' },
    { value: 'Junín', label: 'Junín' },
    { value: 'Tandil', label: 'Tandil' },
    { value: 'Viedma', label: 'Viedma' },
    { value: 'Neuquén', label: 'Neuquén' },
    { value: 'Rio Cuarto', label: 'Rio Cuarto' },
    { value: 'Villa Carlos Paz', label: 'Villa Carlos Paz' },
    { value: 'Ciudad de San Luis', label: 'Ciudad de San Luis' },
    { value: 'Goya', label: 'Goya' },
    { value: 'Formosa', label: 'Formosa' },
    { value: 'Puerto Iguazú', label: 'Puerto Iguazú' },
    { value: 'Gualeguaychu', label: 'Gualeguaychu' },
    { value: 'Sáenz Peña', label: 'Sáenz Peña' },
    { value: 'Rafaela', label: 'Rafaela' },
    { value: 'Quilmes', label: 'Quilmes' },
    { value: 'La banda', label: 'La banda' },
    { value: 'Necochea', label: 'Necochea' },
    { value: 'Villa La Angostura', label: 'Villa La Angostura' },
    { value: 'Caleta Olivia', label: 'Caleta Olivia' },
    { value: 'Villa María', label: 'Villa María' },
    { value: 'San Martin de los Andes', label: 'San Martin de los Andes' },
    { value: 'Rawson', label: 'Rawson' },
    { value: 'Venado Tuerto', label: 'Venado Tuerto' },
  ]

  venezuela = [
    { value: 'Caracas', label: 'Caracas' },
    { value: 'Valencia', label: 'Valencia' },
    { value: 'Ciudad de Córdoba', label: 'Ciudad de Córdoba' },
    { value: 'Puerto La Cruz', label: 'Puerto La Cruz' },
  ]

  colombia = [
    { value: 'Bogotá', label: 'Bogotá' },
    { value: 'Medellín', label: 'Medellín' },
    { value: 'Cali', label: 'Cali' },
    { value: 'Barranquilla', label: 'Barranquilla' },
    { value: 'Cartagena de Indias', label: 'Cartagena de Indias' },
    { value: 'Bucaramanga', label: 'Bucaramanga' },
    { value: 'Santa Marta', label: 'Santa Marta' },
    { value: 'Manizales', label: 'Manizales' },
    { value: 'Cúcuta', label: 'Cúcuta' },
    { value: 'Soacha', label: 'Soacha' },
    { value: 'Soledad', label: 'Soledad' },
    { value: 'Bello', label: 'Bello' },
    { value: 'Pereira', label: 'Pereira' },
    { value: 'Ibagué', label: 'Ibagué' },
    { value: 'Valledupar', label: 'Valledupar' },
    { value: 'Pasto', label: 'Pasto' },
    { value: 'Neiva', label: 'Neiva' },
    { value: 'Armenia', label: 'Armenia' },
    { value: 'Monteria', label: 'Monteria' },
    { value: 'Popayán', label: 'Popayán' },
    { value: 'Tunja', label: 'Tunja' },
    { value: 'Tunja', label: 'Tunja' },
    { value: 'Quibdó', label: 'Quibdó' },
    { value: 'Riohacha', label: 'Riohacha' },
    { value: 'Buenaventura', label: 'Buenaventura' },
    { value: 'Sincelejo', label: 'Sincelejo' },
    { value: 'Florencia', label: 'Florencia' },
    { value: 'Zipaquirá', label: 'Zipaquirá' },
    { value: 'Barrancabemeja', label: 'Barrancabemeja' },
    { value: 'Yopal', label: 'Yopal' },
    { value: 'Villa Soledad', label: 'Villa Soledad' },
    { value: 'Ipiales', label: 'Ipiales' },
    { value: 'Palmira', label: 'Palmira' },
    { value: 'Itagui', label: 'Itagui' },
    { value: 'Rionegro', label: 'Rionegro' },
    { value: 'Envigado', label: 'Envigado' },
    { value: 'Leticia', label: 'Leticia' },
    { value: 'Facatativá', label: 'Facatativá' },
    { value: 'Tuluá', label: 'Tuluá' },
    { value: 'Buga', label: 'Buga' },
    { value: 'Mompós', label: 'Mompós' },
    { value: 'Girardot', label: 'Girardot' },
    { value: 'Tumaco', label: 'Tumaco' },
    { value: 'Apartadó', label: 'Apartadó' },
    { value: 'Duitama', label: 'Duitama' },
    { value: 'Floridablanca', label: 'Floridablanca' },
    { value: 'Jamundí', label: 'Jamundí' },
    { value: 'Mocoa', label: 'Mocoa' },
    { value: 'Yumbo', label: 'Yumbo' },
    { value: 'Ciénaga', label: 'Ciénaga' },
    { value: 'Maicao', label: 'Maicao' },
    { value: 'Turbo', label: 'Turbo' },
  ]
}

export default Cities
