#Frontend
FROM node:18-buster AS build-stage

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY .env ./

COPY . .

RUN yarn run build

FROM nginx:alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon  off;"]
