const AWS_STORAGE = process.env.REACT_APP_AWS_STORAGE
const USER_BUCKET = process.env.REACT_APP_USER_BUCKET
const PET_BUCKET = process.env.REACT_APP_PET_BUCKET
const SERVER = process.env.REACT_APP_SERVER
const HOST = process.env.REACT_APP_HOST
const LIMIT_LIST = 12

export { HOST, SERVER, AWS_STORAGE, LIMIT_LIST, USER_BUCKET, PET_BUCKET }
