export const FORM_STATE = {
  location: {
    city: '',
    country: '',
    lat: 0,
    lng: 0,
    textAddress: '',
  },
  birthday: '',
  name: '',
  sex: '',
  newImages: [],
  images: [],
  category: '',
  adopterUserEmail: '',
  adopted: false,
  description: '',
  medicalNotes: [],
  titleMedicalNote: '',
  detailMedicalNote: '',
};
