export const FORM_STATE = {
  lat: 0,
  lng: 0,
  birthday: "",
  name: "",
  city: "",
  newImages: [],
  sex: "",
  images: [],
  country: "",
  category: "",
  adopterUserEmail: "",
  adopted: false,
  textAddress: "",
  description: "",
  medicalNotes: [],
  titleMedicalNote: "",
  detailMedicalNote: "",
};
