export const petDetailMockup = {
  id: '12345',
  name: 'Buddy',
  category: 'Dog',
  weight: '20 kg',
  breed: 'Golden Retriever',
  description: 'A friendly and energetic dog looking for a loving home.',
  gender: 'Male',
  adopted: false,
  images: ['image1.jpg', 'image2.jpg'],
  size: 'Large',
  location: {
    city: 'Buenos Aires',
  },
  age: '3 years',
  createdAt: new Date(),
  updatedAt: new Date(),
  adoptedBy: '',
  Adopter: '',
  Shelter: '',
  vaccines: [
    {
      id: 'vaccine1',
      name: 'Rabies Vaccine',
      description: 'Protects against rabies',
      vaccinesStatus: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      PetVaccines: ['vaccineRecord1'],
    },

    {
      id: 'vaccine2',
      name: 'Canine Distemper Vaccine',
      description: 'Prevents canine distemper.',
      vaccinesStatus: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      PetVaccines: ['vaccineRecord2'],
    },

    {
      id: 'vaccine3',
      name: 'Feline Leukemia Vaccine',
      description: 'For cats at risk of leukemia.',
      vaccinesStatus: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      PetVaccines: ['vaccineRecord3'],
    },
  ],
  PetsCaredByVolunteer: '',
  MedicalRecord: {
    id: 'record1',
    petId: '12345',
    Pet: 'Buddy',
    date: new Date(),
    description: 'Regular checkup',
    diagnosis: 'Healthy',
    treatment: 'None',
    medications: [],
    followUpRequired: false,
    followUpDate: new Date(),
    veterinarian: 'Dr. Smith',
    clinicName: 'PetCare Clinic',
    notes: 'No issues observed.',
    attachments: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
}
