export const LOGIN = '/login'
export const REGISTER = '/register'
export const RESET_PASSWORD = '/reset-password/:token'
export const FORGOT_PASSWORD = '/forgot-password'
export const HOME = '/'
export const PAGE_NOT_FOUND = '/page-not-found'

export const DASHBOARD = '/dashboard'
export const EDIT_USER = '/edit-user'
export const PROFILE_USER = '/profile-user'
export const PETS_ADOPTER = '/pets-adopted'
export const PROFILE_PET = '/profile-pets'
export const PROFILE = '/profile'
export const CREATE_PET = '/create-pet'
export const EDIT_PET = '/edit-pet'
export const MY_PETS = '/my-pets'
export const SEARCH_VOLANTEERS = '/search-volanteers'
export const SEARCH_PROTECTIONIST = '/search-protectionist'
