export const LOGIN = '/login'
export const REGISTER = '/register'
export const FORGOT_PASSWORD = '/forgot-password'
export const HOME = '/'
export const PAGE_NOT_FOUND = '/page-not-found'

export const DASHBOARD = '/dashboard'
export const USER_PROFILE = '/profile/:id'
export const PETS_ADOPTER = '/pets-adopted'
export const PROFILE_PET = '/profile-pets/:id'
export const PROFILE = '/profile'
export const EDIT_PET = '/create-pet/'
export const CREATE_PET = '/create-pet/:id'
export const MY_PETS = '/my-pets'
export const USER_TRANSIT = '/user-transit'
export const SEARCH_PROTECTIONIST = '/search-protectionist'
